# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
      - GOPATH: /home/circleci/go
    working_directory: /go/src/github.com/goofmint/isaax-hello-world
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go test
  deploy:
    docker:
      - image: circleci/golang:1.9
    environment:
      - GOPATH: /home/circleci/go
    working_directory: /go/src/github.com/goofmint/isaax-hello-world
    steps:
      - checkout
      - run: go build -o dist/main
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${USER_NAME} -r ${REPO_NAME} --replace $(cat VERSION) dist/


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: master